### ISSUE TITLE
Screenshot in README

### ISSUE THREAD

**Issue by luzpaz** [FrViPofm/Bike3D#1]
please? 😄

**Comment by FrViPofm** [comment]
Hi,
Thanks for your interest. This repository was created some hours ago.
I have added some pictures. Maybe I will put one in each folder.
I'm discovering FreeCAD (and CAD in general). Not being an engineer, a programmer, the collection will grow slowly. Advices are welcome.

**Comment by luzpaz** [comment]
Feel free to post your work on the [FreeCAD forums](https://forum.freecadweb.org/viewforum.php?f=24)
